### ISSUE TITLE
Not found target "install_obs_plugin_with_data" (Arch Linux x64)

### ISSUE THREAD

**Issue by mrsteyk** [kc5nra/obs-browser#10]
It happens every time when i want to configure project. I loocked in the cmake files and there is nothing about it on both platforms: Apple an Linux! Help me please!

**Comment by jp9000** [comment]
That particular error hasn't been fixed yet.  It's currently in progress (although slightly paused) on the minor-refactor branch.

That being said, it's currently very difficult to get working on linux due to a design flaw in CEF.  There are still some issues that need to be fixed for this particular plugin to work on linux.

There's an alternate linux version built on qt's webkit here until it's fixed:  https://github.com/bazukas/obs-qtwebkit

Unless you are volunteering to fix those issues, I'd probably recommend closing this pull request.

**Comment by mrsteyk** [comment]
Thanks for alternative jp9000!
