### ISSUE TITLE
Chroma Key Still Not Working

### ISSUE THREAD

**Issue by DeejStar** [kc5nra/obs-browser#18]
Using the Chroma Key filter on my system still has the weird transparent effect even after the bug was supposed to have been fixed.

Last working version for me v1.17

Windows 10 x64
Nvidia GeForce GTX 970 w/ latest drivers
16 GB GDDR3 Ram

**Comment by OsirisNL** [comment]
What weird effect?

**Comment by Draygera** [comment]
![chroma](https://cloud.githubusercontent.com/assets/1167549/13983346/1e440a76-f0bd-11e5-9243-608ef35b51ef.PNG)

The area at the top. I've had this issue since version 1.18, and I've been using a chroma key filter on a banner with with a green background. That banner is a browser source.

**Comment by Draygera** [comment]
This issue seems to have been fixed in Version 1.21. Mind me asking what the issue was to begin with?

**Comment by OsirisNL** [comment]
The problem was that CEF uses pre-multiplied alpha, while OBS uses straight alpha, causing all kinds of weirdness when an alpha channel is involved. Jim (OBS' creator) created a shader that will convert from pre-multiplied alpha to straight alpha, which was included in Studio 0.14.0 and is now used by the Browser Source.

**Comment by Draygera** [comment]
Sweet. Glad I posted this bug report then. Now, does V 1.21 require 0.14.0+ run? Asking a dev that's working on a custom OBS build

**Comment by OsirisNL** [comment]
Yes, 0.14.0 is required.

**Comment by Draygera** [comment]
Thanks again. I'll contact him about it.
