### ISSUE TITLE
Missing widevinecdm.dll

### ISSUE THREAD

**Issue by QuinnDamerell-MS** [kc5nra/obs-browser#70]
Hello! I'm from the Beam team working on OBS Studio FTL (our fork of OBS). I recent updated the browser plugin we include version to 1.29, but some of our users are reporting issues opening OBS. Before the main UI shows, they get an error dialog saying "widevinecdm.dll" is missing from their system. 

(see this thread)
https://github.com/WatchBeam/obs-studio-ftl/issues/77

We use your prebuilt plugin, and I see in your package you include widevinecdmadapter.dll which depends on widevinecdm.dll. But what I can't figure out is why this causes a problem on some users computers and not others. Do you have any suggestions? Is there a reason you don't also package windevinecdm.dll?

**Comment by OsirisNL** [comment]
widevinecdm.dll can't be distributed without permission, I believe.
If you don't need widevine support at all you can just remove widevinecdmadapter.dll

**Comment by QuinnDamerell-MS** [comment]
Do you have any idea what uses it? It's odd that this doesnt seem to happen in OBS proper.

**Comment by OsirisNL** [comment]
I'm not sure, as far as I know only CEF uses it, does it happen when they clean out the plugins folder and reinstall?

**Comment by RytoEX** [comment]
@QuinnDamerell-MS 
Widevine is a DRM solution used with certain video streaming solutions.  If I recall correctly, It's used (required) by Netflix (and a few other streaming services), which is why it's used by CEF.

See these CEF issues:
https://bitbucket.org/chromiumembedded/cef/issues/1631/add-support-for-widevine-cdm
https://bitbucket.org/chromiumembedded/cef/issues/2009/dont-download-widevine-cdm-using-component

**Comment by QuinnDamerell-MS** [comment]
@RytoEX thanks for the info. 

@OsirisNL so if I remove the widevinecdmadapter.dll it will silently fail when loading and not render the encrypted content? I'm fine with that because I don't think many of our users need encrypted video in OBS.

**Comment by OsirisNL** [comment]
You can just remove it yeah.
