### ISSUE TITLE
It's 2017 can we --enable-gpu by default yet?

### ISSUE THREAD

**Issue by gigablox** [kc5nra/obs-browser#80]
We have a "soon-to-launch" service which enables users to display `webGL` based content using OBS and other streaming applications. OBS unfortunately still forces users to set a flag in their startup links `--enable-gpu`.

Making this flag a manual setting is hindering innovation by forcing services to use deprecated fallbacks like Canvas for users not knowledgeable enough or willing to enable this setting manually.

PC's which are able and ready to use `webGL` are wasting CPU cycles and **hurting the performance of OBS by using Canvas polyfills.**

Just recently, Canvas renderer has been abstracted and marked as deprecated by the ThreeJS library, which means this polyfill will not even be an option for future ThreeJS versions to come - this will severally limit future development capabilities.

I think the majority of users now will have PC's well equipped for enabling GPU by default. I think, at this point in time we should be manually setting a flag that does quite the opposite...

`--disable-gpu`

**Comment by Lange** [comment]
I am not a maintainer of this project but I'm going to stick up for them and say that you entering this thread and demanding free labor from people so that you may build your service on top of it is rude and exactly the type of toxicity that harms open source.

To directly address your question, there are roadblocks to enabling GPU support. You can read https://github.com/kc5nra/obs-browser/issues/45 for more information on this. The summary is that there appear to be issues in CEF itself when using GPU with OSR (off-screen rendering).

**Comment by gigablox** [comment]
@Lange I think every issue at it's core has a point of frustration - but the way I laid it out here isn't "rude" or "toxic" or "hurt open source". Nowhere in my ticket did I "demand free labor".

**Comment by VodBox** [comment]
Coming in and saying "It's the current year, why hasn't this thing been done yet?" and alleging that the maintainers are hindering innovation is rude no matter how much you might want to claim otherwise.

Without those things, the issue raised is still the same, and the answer would still be the same - Not yet, until issues regarding CEF and OSR are fixed.

Instead, on top of that you choose to imply the maintainers are either incompetent, slow, or actively malicious towards developers who want WebGL.

**Comment by gigablox** [comment]
@VodBox My post was well constructed and informative - the tone I set in the title led to gross over-reactions. I stand by the title of the question because sometimes you need to communicate frustration with some obvious truths.

It's 2017 and `webGL` support is something OBS still doesn't have worked out.

I stand by my statement that the technology is hindering innovation. 

Not because it's a claim - because it's a fact and my current reality.

**Comment by dodgepong** [comment]
GPU-accelerated rendering is disabled by default not because "people don't have good enough PCs". As both Lange and VodBox mentioned, [there are some serious issues with CEF and off-screen rendering performance](https://bitbucket.org/chromiumembedded/cef/issues/2046/improve-gpu-readback-performance-for-osr). If you want to blame someone, blame CEF, not OBS.

For more reading, also check out [this other CEF issue](https://bitbucket.org/chromiumembedded/cef/issues/1006/cef3-support-rendering-to-a-hardware-gl) and [this pull request to address the issue](https://bitbucket.org/chromiumembedded/cef/pull-requests/96/osr-fix-gpu-cpu-readback-performance/diff) (which has not been merged yet), as well as issue #45 that Lange linked to.

**Comment by jp9000** [comment]
Let's all try to keep a cool head.  I am very grateful for the support, though I don't think he's particularly intending to be rude or insulting, he's not really name-calling or anything, he's just frustrated and doesn't understand why we have it set up this way, so let's try to all go easy on each other.  It's really just a misunderstanding, he probably isn't aware the off-screen rendering issue.

As has been stated in that other issue, this is indeed due to an off-screen rendering issue with CEF.  Currently, having --enable-gpu on actually gives worse performance under more circumstances than having it off.  We of course don't want to have to have it disabled at all, it's just a flaw in CEF off-screen rendering at the moment (at least from what I recall, I don't maintain the browser plugin personally so I'm not fully up-to-date on the issue).

The CEF project itself currently has a pull request trying to fix this specific issue, but it hasn't been merged or fully vetted yet.  I realize that you may need some features that having it provides, but know at the very least that we do have a good reason for doing what we're doing.  For the mean time I would recommend trying to find some means of working around the issue if possible -- I realize that it's somewhat of a roadblock for you, but we're both stuck between a rock and a hard place.

If there's a means of enabling this and still keeping the browser source rendering at the proper framerate, we'll use it in an instant.  I will look in to it myself, though I can't promise anything.

**Comment by gigablox** [comment]
Thanks for your time @jp9000. I was not aware CEF was the bottleneck here. Keep up the good work.
