### ISSUE TITLE
outdated Chrome Version

### ISSUE THREAD

**Issue by jumoog** [kc5nra/obs-browser#85]
Chrome 57.0.2987.0 is pretty old current version is 59.0.3071.115

**Comment by dodgepong** [comment]
v57 is only a few months old. What do you need in v59 that you are currently missing?

Also, it's worth noting that, due to its size, it's generally advisable not to push out browser source updates too frequently lest the update size be too large for users. I know 100MB might not sound like a lot, but it can be annoying for users on limited data plans or on slow connections, not to mention bandwidth costs on the patch server.

**Comment by jumoog** [comment]
maybe some fixed security stuff but yeah it got your point.. i'll build myself
